project:
  type: website

format:
  html:
    theme: pulse  

execute:     
  echo: false
  message: false
  warning: false
  freeze: auto

knitr:
  opts_chunk:
    dev: "ragg_png"   

date-format: iso    